server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sav_tickets
    username: sav_user
    password: sav_password
    driver-class-name: org.postgresql.Driver
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2:1b
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view:  false
  kafka:
    consumer:
      properties:
        spring.json.type.mapping: agentAssigned:com.emsi.sav.servicetickets.events.AgentAssignedEvent
    producer:
      properties:
        spring.json.type.mapping: ticketCreated:com.emsi.sav.servicetickets.events.TicketCreatedEvent,ticketResolved:com.emsi.sav.servicetickets.events.TicketResolvedEvent
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always